import { Patient, Doctor, Employee, Queue, MedicalRecord, ReferralLetter, Medicine, Transaction, ActivityLog, ClinicProfile, RolePermission } from '../types';

export const initialPatients: Patient[] = [
  {
    id: 'P001',
    name: 'Budi Santoso',
    nik: '3171021405820003',
    bpjsNumber: '0001234567890',
    type: 'BPJS',
    gender: 'Laki-laki',
    birthDate: '1982-05-14',
    phone: '081234567890',
    address: 'Jl. Merdeka No. 45, Jakarta Pusat',
    registerDate: '2026-01-10',
    bpjsStatus: 'Aktif',
    bpjsClass: 'Kelas 1',
  },
  {
    id: 'P002',
    name: 'Siti Rahmawati',
    nik: '3173055812900004',
    bpjsNumber: '0009876543210',
    type: 'BPJS',
    gender: 'Perempuan',
    birthDate: '1990-12-18',
    phone: '085712345678',
    address: 'Jl. Kenanga Raya No. 12, Jakarta Timur',
    registerDate: '2026-01-22',
    bpjsStatus: 'Aktif',
    bpjsClass: 'Kelas 2',
  },
  {
    id: 'P003',
    name: 'Andi Wijaya',
    nik: '3275062507950002',
    type: 'Umum',
    gender: 'Laki-laki',
    birthDate: '1995-07-25',
    phone: '089988776655',
    address: 'Perumahan Indah Permai Blok B2, Bekasi',
    registerDate: '2026-02-05',
    bpjsStatus: 'Belum Dicek',
  },
  {
    id: 'P004',
    name: 'Dewi Lestari',
    nik: '3174094203880001',
    bpjsNumber: '0002468135790',
    type: 'BPJS',
    gender: 'Perempuan',
    birthDate: '1988-03-02',
    phone: '081388990011',
    address: 'Jl. Mawar Gg. 3 No. 8, Jakarta Selatan',
    registerDate: '2026-02-14',
    bpjsStatus: 'Tidak Aktif',
    bpjsClass: 'Kelas 3',
  },
  {
    id: 'P005',
    name: 'Eko Prasetyo',
    nik: '3374011002850005',
    type: 'Umum',
    gender: 'Laki-laki',
    birthDate: '1985-02-10',
    phone: '082155443322',
    address: 'Jl. Dahlia No. 17, Semarang',
    registerDate: '2026-03-01',
    bpjsStatus: 'Belum Dicek',
  },
  {
    id: 'P006',
    name: 'Rina Wahyuni',
    nik: '3171056509930008',
    bpjsNumber: '0003579124680',
    type: 'BPJS',
    gender: 'Perempuan',
    birthDate: '1993-09-25',
    phone: '087822334455',
    address: 'Sunter Residence Tower B Lt. 5, Jakarta Utara',
    registerDate: '2026-03-12',
    bpjsStatus: 'Aktif',
    bpjsClass: 'Kelas 1',
  }
];

export const initialDoctors: Doctor[] = [
  {
    id: 'D001',
    name: 'dr. Agus Hermawan, Sp.PD',
    specialist: 'Spesialis Penyakit Dalam',
    sip: 'SIP/2022/4523-01/Sp.PD',
    room: 'Poli Dalam - Ruang 101',
    onDuty: true,
    schedule: {
      Senin: '08:00 - 13:00',
      Selasa: '08:00 - 13:00',
      Rabu: '08:00 - 13:00',
      Kamis: '14:00 - 18:00',
      Jumat: '08:00 - 13:00',
    }
  },
  {
    id: 'D002',
    name: 'dr. Rian Sugiarto, Sp.A',
    specialist: 'Spesialis Anak',
    sip: 'SIP/2021/8712-02/Sp.A',
    room: 'Poli Anak - Ruang 102',
    onDuty: true,
    schedule: {
      Senin: '09:00 - 14:00',
      Rabu: '14:00 - 18:00',
      Kamis: '09:00 - 14:00',
      Sabtu: '09:00 - 13:00',
    }
  },
  {
    id: 'D003',
    name: 'dr. Farah Medina, Sp.OG',
    specialist: 'Spesialis Kebidanan & Kandungan',
    sip: 'SIP/2023/1129-03/Sp.OG',
    room: 'Poli Kandungan - Ruang 103',
    onDuty: false,
    schedule: {
      Selasa: '14:00 - 19:00',
      Kamis: '08:00 - 12:00',
      Jumat: '14:00 - 19:00',
    }
  },
  {
    id: 'D004',
    name: 'dr. Hendra Wijaya, GP',
    specialist: 'Dokter Umum',
    sip: 'SIP/2020/3011-04/Umum',
    room: 'Poli Umum - Ruang 104',
    onDuty: true,
    schedule: {
      Senin: '08:00 - 16:00',
      Selasa: '08:00 - 16:00',
      Rabu: '08:00 - 16:00',
      Kamis: '08:00 - 16:00',
      Jumat: '08:00 - 16:00',
      Sabtu: '13:00 - 18:00',
    }
  }
];

export const initialEmployees: Employee[] = [
  {
    id: 'K001',
    name: 'Supardi Hartono',
    nip: 'NIP.19850112.201012.1.001',
    role: 'Admin',
    email: 'supardi@klinikmedika.com',
    phone: '081299887766',
    status: 'Aktif',
    password: 'admin'
  },
  {
    id: 'K002',
    name: 'dr. Agus Hermawan, Sp.PD',
    nip: 'NIP.19780514.200501.1.003',
    role: 'Dokter',
    email: 'agus.hermawan@klinikmedika.com',
    phone: '081122334455',
    status: 'Aktif',
    password: 'dokter'
  },
  {
    id: 'K003',
    name: 'Suster Rini Karlina',
    nip: 'NIP.19920918.201608.2.012',
    role: 'Perawat',
    email: 'rini.karlina@klinikmedika.com',
    phone: '085233445566',
    status: 'Aktif',
    password: 'perawat'
  },
  {
    id: 'K004',
    name: 'Apoteker Laras Astuti',
    nip: 'NIP.19900312.201501.2.008',
    role: 'Apoteker',
    email: 'laras.astuti@klinikmedika.com',
    phone: '081399881122',
    status: 'Aktif',
    password: 'apoteker'
  },
  {
    id: 'K005',
    name: 'Yanti Kumalasari',
    nip: 'NIP.19940711.201804.2.025',
    role: 'Kasir',
    email: 'yanti.k@klinikmedika.com',
    phone: '088899001122',
    status: 'Aktif',
    password: 'kasir'
  },
  {
    id: 'K006',
    name: 'Budi Santoso',
    nip: 'NIP.PASIEN001',
    role: 'Pasien',
    email: 'budi.santoso@gmail.com',
    phone: '081234567890',
    status: 'Aktif'
  }
];

export const initialMedicines: Medicine[] = [
  {
    id: 'M001',
    name: 'Paracetamol 500mg',
    code: 'OB-PCT-500',
    category: 'Analgesik & Antipiretik',
    stock: 450,
    minStock: 100,
    unit: 'Tablet',
    price: 500,
    expiryDate: '2028-04-12',
    type: 'Obat',
  },
  {
    id: 'M002',
    name: 'Amoxicillin 500mg',
    code: 'OB-AMX-500',
    category: 'Antibiotik Penicillin',
    stock: 80,
    minStock: 100,
    unit: 'Tablet',
    price: 1200,
    expiryDate: '2027-09-20',
    type: 'Obat',
  },
  {
    id: 'M003',
    name: 'Metformin HCl 500mg',
    code: 'OB-MET-500',
    category: 'Antidiabetes Oral',
    stock: 320,
    minStock: 50,
    unit: 'Tablet',
    price: 800,
    expiryDate: '2028-01-15',
    type: 'Obat',
  },
  {
    id: 'M004',
    name: 'Antasida Doen',
    code: 'OB-ANT-001',
    category: 'Antasida & Antiulserasi',
    stock: 15,
    minStock: 50,
    unit: 'Botol Sirup',
    price: 6500,
    expiryDate: '2026-11-30',
    type: 'Obat',
  },
  {
    id: 'M005',
    name: 'Amlodipine 5mg',
    code: 'OB-AML-005',
    category: 'Antihipertesi',
    stock: 500,
    minStock: 100,
    unit: 'Tablet',
    price: 600,
    expiryDate: '2028-06-01',
    type: 'Obat',
  },
  {
    id: 'M051',
    name: 'Spuit Suntik 3cc',
    code: 'BM-SPT-3CC',
    category: 'Alat Kesehatan & Medis',
    stock: 150,
    minStock: 30,
    unit: 'Pcs',
    price: 3500,
    expiryDate: '2029-12-31',
    type: 'Non Obat',
  },
  {
    id: 'M052',
    name: 'Masker Medis 3-Ply',
    code: 'BM-MSK-3PL',
    category: 'Alat Kesehatan & Medis',
    stock: 200,
    minStock: 40,
    unit: 'Box',
    price: 25000,
    expiryDate: '2028-10-15',
    type: 'Non Obat',
  },
  {
    id: 'M006',
    name: 'OBH Sirup 100ml',
    code: 'OB-OBH-100',
    category: 'Obat Batuk & Pilek',
    stock: 45,
    minStock: 20,
    unit: 'Botol',
    price: 15000,
    expiryDate: '2027-12-10',
    type: 'Obat',
  }
];

export const initialQueues: Queue[] = [
  {
    id: 'Q001',
    queueNumber: 'A-01',
    patientId: 'P001',
    patientName: 'Budi Santoso',
    patientType: 'BPJS',
    doctorId: 'D001',
    doctorName: 'dr. Agus Hermawan, Sp.PD',
    room: 'Poli Dalam - Ruang 101',
    status: 'Selesai',
    datetime: '2026-06-01T08:15:00Z'
  },
  {
    id: 'Q002',
    queueNumber: 'B-01',
    patientId: 'P002',
    patientName: 'Siti Rahmawati',
    patientType: 'BPJS',
    doctorId: 'D002',
    doctorName: 'dr. Rian Sugiarto, Sp.A',
    room: 'Poli Anak - Ruang 102',
    status: 'Diperiksa',
    datetime: '2026-06-01T08:30:00Z'
  },
  {
    id: 'Q003',
    queueNumber: 'C-01',
    patientId: 'P003',
    patientName: 'Andi Wijaya',
    patientType: 'Umum',
    doctorId: 'D004',
    doctorName: 'dr. Hendra Wijaya, GP',
    room: 'Poli Umum - Ruang 104',
    status: 'Menunggu',
    datetime: '2026-06-01T08:45:00Z'
  },
  {
    id: 'Q004',
    queueNumber: 'A-02',
    patientId: 'P004',
    patientName: 'Dewi Lestari',
    patientType: 'BPJS',
    doctorId: 'D001',
    doctorName: 'dr. Agus Hermawan, Sp.PD',
    room: 'Poli Dalam - Ruang 101',
    status: 'Menunggu',
    datetime: '2026-06-01T08:50:00Z'
  },
  {
    id: 'Q005',
    queueNumber: 'C-02',
    patientId: 'P005',
    patientName: 'Eko Prasetyo',
    patientType: 'Umum',
    doctorId: 'D004',
    doctorName: 'dr. Hendra Wijaya, GP',
    room: 'Poli Umum - Ruang 104',
    status: 'Menunggu',
    datetime: '2026-06-01T09:10:00Z'
  }
];

export const initialMedicalRecords: MedicalRecord[] = [
  {
    id: 'MR001',
    patientId: 'P001',
    patientName: 'Budi Santoso',
    doctorId: 'D001',
    doctorName: 'dr. Agus Hermawan, Sp.PD',
    date: '2026-06-01',
    complaints: 'Nyeri lambung parah, mual, dan pusing sejak 3 hari lalu. Sering telat makan.',
    physicalExam: {
      bloodPressure: '120/80',
      temperature: 36.8,
      pulseRate: 82,
      weight: 71,
    },
    diagnosis: 'Gastritis Akut (Maag) & Dyspepsia',
    treatment: 'Edukasi diet teratur, injeksi antasida, dan pemberian resep obat jalan.',
    prescribedMeds: [
      { id: 'M004', name: 'Antasida Doen', qty: 1, usage: '3x Sehari 1 sendok makan, 1 jam sebelum makan' },
      { id: 'M001', name: 'Paracetamol 500mg', qty: 10, usage: '3x Sehari 1 tablet bila pusing atau demam' }
    ]
  },
  {
    id: 'MR002',
    patientId: 'P001',
    patientName: 'Budi Santoso',
    doctorId: 'D001',
    doctorName: 'dr. Agus Hermawan, Sp.PD',
    date: '2026-05-15',
    complaints: 'Kontrol tekanan darah, leher terasa tegang di sore hari.',
    physicalExam: {
      bloodPressure: '145/95',
      temperature: 36.5,
      pulseRate: 75,
      weight: 71.5,
    },
    diagnosis: 'Hipertensi Esensial Essential Stage 1',
    treatment: 'Edukasi kurangi konsumsi garam, olahraga teratur 30 menit sehari.',
    prescribedMeds: [
      { id: 'M005', name: 'Amlodipine 5mg', qty: 30, usage: '1x Sehari 1 tablet di malam hari' }
    ]
  },
  {
    id: 'MR003',
    patientId: 'P004',
    patientName: 'Dewi Lestari',
    doctorId: 'D001',
    doctorName: 'dr. Agus Hermawan, Sp.PD',
    date: '2026-05-28',
    complaints: 'Nyeri dada menjalar ke lengan kiri disertai sesak napas saat beraktivitas berat.',
    physicalExam: {
      bloodPressure: '150/90',
      temperature: 36.7,
      pulseRate: 95,
      weight: 65,
    },
    diagnosis: 'Susp. Ischemic Heart Disease (Angina Pectoris)',
    treatment: 'Stabilisasi awal, oksigenasi 2 lpm, berikan rujukan darurat ke RS Jantung Harapan.',
    prescribedMeds: [],
    referralId: 'REF001'
  }
];

export const initialReferralLetters: ReferralLetter[] = [
  {
    id: 'REF001',
    medicalRecordId: 'MR003',
    patientId: 'P004',
    patientName: 'Dewi Lestari',
    patientNik: '3174094203880001',
    patientBpjsNumber: '0002468135790',
    gender: 'Perempuan',
    birthDate: '1988-03-02',
    diagnosis: 'Susp. Ischemic Heart Disease (Angina Pectoris) / Penyakit Jantung Koroner',
    destinationHospital: 'RS Pusat Jantung Nasional Harapan Kita',
    targetSpecialist: 'Spesialis Jantung & Pembuluh Darah (Kardiologi)',
    notes: 'Mohon tatalaksana diagnostik dan evaluasi lanjutan (EKG Treadmill / Kateterisasi). Kondisi stabil, vital sign dilampirkan.',
    dateIssued: '2026-05-28',
    doctorSignName: 'dr. Agus Hermawan, Sp.PD',
    doctorSip: 'SIP/2022/4523-01/Sp.PD'
  }
];

export const initialTransactions: Transaction[] = [
  {
    id: 'T001',
    invoiceNumber: 'INV/20260601/001',
    type: 'Uang Masuk',
    category: 'Pendaftaran & Konsultasi',
    amount: 150000,
    date: '2026-06-01',
    description: 'Biaya konsultasi pasien umum Andi Wijaya (GP)',
    payerOrPayee: 'Andi Wijaya'
  },
  {
    id: 'T002',
    invoiceNumber: 'INV/20260601/002',
    type: 'Uang Masuk',
    category: 'Klaim BPJS Kesehatan',
    amount: 1850000,
    date: '2025-05-28',
    description: 'Pencairan klaim BPJS Kesehatan Rawat Jalan periode April 2026',
    payerOrPayee: 'BPJS Kesehatan Kantor Cabang Utama'
  },
  {
    id: 'T003',
    invoiceNumber: 'INV/20260530/010',
    type: 'Uang Keluar',
    category: 'Pembelian Obat & BMHP',
    amount: 450000,
    date: '2026-05-30',
    description: 'Restocking Paracetamol 500mg dan Spuit 3cc dari PBF Kimia Farma',
    payerOrPayee: 'PT Kimia Farma Trading & Distribution'
  },
  {
    id: 'T004',
    invoiceNumber: 'INV/20260525/002',
    type: 'Uang Keluar',
    category: 'Biaya Operasional',
    amount: 950000,
    date: '2026-05-25',
    description: 'Pembayaran listrik PLN pascabayar & tagihan Internet Indihome Mei 2026',
    payerOrPayee: 'PT PLN & PT Telkom Indonesia'
  },
  {
    id: 'T005',
    invoiceNumber: 'INV/20260601/003',
    type: 'Uang Masuk',
    category: 'Pelayanan Obat & Apotek',
    amount: 65000,
    date: '2026-06-01',
    description: 'Penjualan obat resep non-BPJS pasien umum - Paracetamol & Vitamin',
    payerOrPayee: 'Andi Wijaya'
  }
];

export const initialActivityLogs: ActivityLog[] = [
  {
    id: 'L001',
    userId: 'K001',
    userName: 'Supardi Hartono',
    userRole: 'Admin',
    action: 'Login System',
    details: 'Melakukan login ke portal admin klinik menggunakan perangkat Chrome Desktop',
    timestamp: '2026-06-01T07:30:00Z'
  },
  {
    id: 'L002',
    userId: 'K003',
    userName: 'Suster Rini Karlina',
    userRole: 'Perawat',
    action: 'Pendaftaran Pasien',
    details: 'Mendaftarkan pasien baru atas nama Eko Prasetyo kategori Umum',
    timestamp: '2026-06-01T07:45:00Z'
  },
  {
    id: 'L003',
    userId: 'K003',
    userName: 'Suster Rini Karlina',
    userRole: 'Perawat',
    action: 'Registrasi Antrean',
    details: 'Menambahkan pasien Budi Santoso (BPJS) ke antrean Poli Dalam (A-01)',
    timestamp: '2026-06-01T08:00:00Z'
  },
  {
    id: 'L004',
    userId: 'K002',
    userName: 'dr. Agus Hermawan, Sp.PD',
    userRole: 'Dokter',
    action: 'Penginputan Rekam Medis',
    details: 'Menginput rekam medis pemeriksaan, diagnosis Maag parah bagi Budi Santoso (P001)',
    timestamp: '2026-06-01T08:15:00Z'
  },
  {
    id: 'L005',
    userId: 'K004',
    userName: 'Apoteker Laras Astuti',
    userRole: 'Apoteker',
    action: 'Pengeluaran Obat',
    details: 'Memverifikasi resep MR001 dan memotong stok ketersediaan Antasida dan Paracetamol',
    timestamp: '2026-06-01T08:22:00Z'
  },
  {
    id: 'L006',
    userId: 'K005',
    userName: 'Yanti Kumalasari',
    userRole: 'Kasir',
    action: 'Penerimaan Pembayaran',
    details: 'Menerima pembayaran tunai senilai Rp150.000 untuk resep & jasa Andi Wijaya (INV/20260601/001)',
    timestamp: '2026-06-01T08:45:00Z'
  }
];

export const defaultClinicProfile: ClinicProfile = {
  name: 'Klinik Pratama Sehat Utama',
  tagline: 'Pelayanan Kesehatan Ramah, Cepat, dan Terpercaya',
  address: 'Jl. Boulevard Raya Barat No. 128, Kelapa Gading, Jakarta Utara 14240',
  phone: '021-45871234 / 0811-9876-5432',
  email: 'info@sehatutama.id',
  website: 'www.sehatutama.id',
  logo: '🏥' // Standard beautiful clinical emoji as default logo
};

export const defaultPermissions: RolePermission[] = [
  {
    role: 'Admin',
    description: 'Superuser dengan akses tak terbatas untuk mengatur seluruh operasional klinik.',
    canManagePatients: true,
    canManageMedicalRecords: true,
    canManageSchedules: true,
    canManageInventory: true,
    canManageFinance: true,
    canManageEmployees: true,
    canViewQueues: true,
    canCallQueues: true,
    canViewDashboard: true,
    canViewPatientsList: true,
    canViewMedicalRecordsAndReferrals: true,
    canViewDoctorSchedules: true,
    canViewMedicineInventory: true,
    canViewFinancialReports: true,
    canViewEmployeeList: true,
    canViewBPJSChecker: true,
    canViewActivityLog: true,
    canViewClinicSettings: true,
    canManagePendaftaranQueue: true,
    canManageKasirQueue: true,
    canManageObatQueue: true,
    canViewMonitorTVLobby: true,
    canManageClinicProfileAndLogo: true,
    canManageThemeColorSchema: true,
    canManageRoleAccessMatrix: true,
    canManageQueueSetup: true,
  },
  {
    role: 'Dokter',
    description: 'Pemeriksaan pasien, pengisian rekam medis, pemberian resep, dan pembuatan rujukan.',
    canManagePatients: true,
    canManageMedicalRecords: true,
    canManageSchedules: false,
    canManageInventory: false,
    canManageFinance: false,
    canManageEmployees: false,
    canViewQueues: true,
    canCallQueues: true,
    canViewDashboard: true,
    canViewPatientsList: true,
    canViewMedicalRecordsAndReferrals: true,
    canViewDoctorSchedules: true,
    canViewMedicineInventory: true,
    canViewFinancialReports: false,
    canViewEmployeeList: false,
    canViewBPJSChecker: true,
    canViewActivityLog: false,
    canViewClinicSettings: false,
    canManagePendaftaranQueue: true,
    canManageKasirQueue: false,
    canManageObatQueue: false,
    canViewMonitorTVLobby: true,
    canManageClinicProfileAndLogo: false,
    canManageThemeColorSchema: false,
    canManageRoleAccessMatrix: false,
    canManageQueueSetup: false,
  },
  {
    role: 'Perawat',
    description: 'Pendaftaran pasien, pemeriksaan tanda vital awal (anamnesa), dan pengelolaan antrean.',
    canManagePatients: true,
    canManageMedicalRecords: false,
    canManageSchedules: true,
    canManageInventory: true,
    canManageFinance: false,
    canManageEmployees: false,
    canViewQueues: true,
    canCallQueues: true,
    canViewDashboard: true,
    canViewPatientsList: true,
    canViewMedicalRecordsAndReferrals: true,
    canViewDoctorSchedules: true,
    canViewMedicineInventory: true,
    canViewFinancialReports: false,
    canViewEmployeeList: false,
    canViewBPJSChecker: true,
    canViewActivityLog: false,
    canViewClinicSettings: false,
    canManagePendaftaranQueue: true,
    canManageKasirQueue: false,
    canManageObatQueue: false,
    canViewMonitorTVLobby: true,
    canManageClinicProfileAndLogo: false,
    canManageThemeColorSchema: false,
    canManageRoleAccessMatrix: false,
    canManageQueueSetup: false,
  },
  {
    role: 'Apoteker',
    description: 'Pemberian obat berdasarkan resep dokter, pengelolaan inventaris obat, dan expired date.',
    canManagePatients: false,
    canManageMedicalRecords: false,
    canManageSchedules: false,
    canManageInventory: true,
    canManageFinance: false,
    canManageEmployees: false,
    canViewQueues: true,
    canCallQueues: false,
    canViewDashboard: true,
    canViewPatientsList: false,
    canViewMedicalRecordsAndReferrals: false,
    canViewDoctorSchedules: true,
    canViewMedicineInventory: true,
    canViewFinancialReports: false,
    canViewEmployeeList: false,
    canViewBPJSChecker: true,
    canViewActivityLog: false,
    canViewClinicSettings: false,
    canManagePendaftaranQueue: false,
    canManageKasirQueue: false,
    canManageObatQueue: true,
    canViewMonitorTVLobby: true,
    canManageClinicProfileAndLogo: false,
    canManageThemeColorSchema: false,
    canManageRoleAccessMatrix: false,
    canManageQueueSetup: false,
  },
  {
    role: 'Kasir',
    description: 'Manajemen kasir pembayaran non-BPJS dan pencetakan kuitansi kuitansi transaksi keuangan.',
    canManagePatients: false,
    canManageMedicalRecords: false,
    canManageSchedules: false,
    canManageInventory: false,
    canManageFinance: true,
    canManageEmployees: false,
    canViewQueues: true,
    canCallQueues: false,
    canViewDashboard: true,
    canViewPatientsList: false,
    canViewMedicalRecordsAndReferrals: false,
    canViewDoctorSchedules: true,
    canViewMedicineInventory: false,
    canViewFinancialReports: true,
    canViewEmployeeList: false,
    canViewBPJSChecker: true,
    canViewActivityLog: false,
    canViewClinicSettings: false,
    canManagePendaftaranQueue: false,
    canManageKasirQueue: true,
    canManageObatQueue: false,
    canViewMonitorTVLobby: true,
    canManageClinicProfileAndLogo: false,
    canManageThemeColorSchema: false,
    canManageRoleAccessMatrix: false,
    canManageQueueSetup: false,
  },
  {
    role: 'Pasien',
    description: 'Melihat antrean aktif, jadwal dokter, profil rekam medis mandiri, dan unduh rujukan.',
    canManagePatients: false,
    canManageMedicalRecords: false,
    canManageSchedules: false,
    canManageInventory: false,
    canManageFinance: false,
    canManageEmployees: false,
    canViewQueues: true,
    canCallQueues: false,
    canViewDashboard: true,
    canViewPatientsList: false,
    canViewMedicalRecordsAndReferrals: false,
    canViewDoctorSchedules: true,
    canViewMedicineInventory: false,
    canViewFinancialReports: false,
    canViewEmployeeList: false,
    canViewBPJSChecker: false,
    canViewActivityLog: false,
    canViewClinicSettings: false,
    canManagePendaftaranQueue: false,
    canManageKasirQueue: false,
    canManageObatQueue: false,
    canViewMonitorTVLobby: true,
    canManageClinicProfileAndLogo: false,
    canManageThemeColorSchema: false,
    canManageRoleAccessMatrix: false,
    canManageQueueSetup: false,
  }
];
